version: '2'

services:
  postgres:
    image: 'postgres:9.6'
    restart: always
    environment:
      POSTGRES_USER: 'hpi'
      POSTGRES_PASSWORD: '${POSTGRES_PASS}'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  web:
    restart: always
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3001:3000'
    volumes:
      - '.:/openhpigame'
    env_file:
      - '.env'

  nginx:
    image: nginx
    restart: always
    links:
      - web:web
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    volumes_from:
      - web

    ports:
     - "80:80"


volumes:
  postgres:
