# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c309dbe70f2e21f0c300407731bdd0f8369cb39252f462dbcc6c6c5e65e3e43e00f26158c48614a7c559d38b153201f1246e66c48d5f5a895103c06a5ad8791

test:
  secret_key_base: 1c9dbd3f596422fc79697e002e0c55765f0d12275eec47350820e9b0f49f1729d5ae910cef23bdfbef75d11e2cbb4f15467ee4ad55934a0c0f2d301cfdd3fa6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
